version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    container_name: shopsite-mysql
    restart: always
    environment:
      # 直接引用 .env 文件中的变量
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

volumes:
  db_data: